name: Terraform DEV

on:
  push:
    branches:
      - dev

jobs:

  terraform:

    runs-on:
      - self-hosted
      - dev

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-2

      - name: Terraform Init
        run: |
          cd env/dev
          terraform init

      - name: Terraform Validate
        run: |
          cd env/dev
          terraform validate

      - name: Terraform Plan
        run: |
          cd env/dev
          terraform plan

      - name: Terraform Apply
        run: |
          cd env/dev
          terraform apply -auto-approve