name: Terraform DEV

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        type: choice
        description: Action to perform
        default: Apply
        options:
          - Apply
          - Destroy

jobs:

  terraform:

    runs-on:
      - self-hosted
      - dev

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-2

      - name: Terraform Init
        run: |
          cd env/test
          terraform init

      - name: Terraform Validate
        run: |
          cd env/test
          terraform validate

      - name: Terraform Plan
        run: |
          cd env/test
          terraform plan

      - name: Terraform Apply
        if: ${{ github.event.inputs.terraform_action == 'Apply' }}
        run: |
            cd env/dev
            terraform apply -auto-approve

      - name: Terraform Destroy
        if: ${{ github.event.inputs.terraform_action == 'Destroy' }}
        run: |
            cd env/dev
            terraform destroy -auto-approve